include:
  - authelia/docker-compose.yml
  - traefik/docker-compose.yml

services:
  courses:
    image: ghcr.io/imirjar/poliglotim-api:latest
    container_name: poliglotim-api
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PORT: "6060"
      DB_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${PLYGLO_DB}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.courses.rule=Host(`api.plyglo.com`)"
      - "traefik.http.routers.courses.entrypoints=websecure"
      - "traefik.http.routers.courses.tls=true"
      - "traefik.http.routers.courses.tls.certresolver=letsencrypt"
      - "traefik.http.routers.courses.middlewares=chain-api@file"     # ← было authelia@docker
      - "traefik.http.services.courses.loadbalancer.server.port=6060"
    networks:
      - platform-network

  site:
    image: ghcr.io/imirjar/plyglo-website:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`plyglo.com`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.routers.site.tls=true"
      - "traefik.http.routers.site.tls.certresolver=letsencrypt"     # ← добавили
      - "traefik.http.routers.site.middlewares=chain-no-auth@file"   # ← публичный
      - "traefik.http.services.site.loadbalancer.server.port=80"     # ← было 443, у вас nginx :80
    networks:
      - platform-network

  app:
    image: ghcr.io/imirjar/plyglo-study:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`study.plyglo.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"      # ← добавили
      - "traefik.http.routers.app.middlewares=chain-no-auth@file"    # ← публичный
      - "traefik.http.services.app.loadbalancer.server.port=80"      # ← Caddy, если редиректит — см. п.5 ниже
    networks:
      - platform-network

networks:
  platform-network:
    driver: bridge