include:
  - auth/docker-compose.yml
  - traefik/docker-compose.yml

services:
  courses:
    image: ghcr.io/imirjar/poliglotim-api:latest
    container_name: courses
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      PORT: "6060"
      DB_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${PLYGLO_DB}
    labels:
      - "traefik.enable=true"
      # Роутер для v1
      - "traefik.http.routers.courses.rule=Host(`api.plyglo.com`) && PathPrefix(`/v1`)"
      - "traefik.http.routers.courses.entrypoints=websecure"
      - "traefik.http.routers.courses.tls=true"
      - "traefik.http.routers.courses.tls.certresolver=letsencrypt"
      - "traefik.http.routers.courses.middlewares=strip-v1" # chain-api@file можно оставить
      - "traefik.http.services.courses.loadbalancer.server.port=6060"
      # Middleware для удаления префикса /v1
      - "traefik.http.middlewares.strip-v1.stripprefix.prefixes=/v1"
    networks:
      - platform-network

  site:
    image: ghcr.io/imirjar/plyglo-website:latest
    container_name: site
    platform: linux/amd64
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.rule=Host(`plyglo.com`)"
      - "traefik.http.routers.site.entrypoints=websecure"
      - "traefik.http.routers.site.tls=true"
      - "traefik.http.routers.site.tls.certresolver=letsencrypt"
      - "traefik.http.routers.site.middlewares=chain-no-auth@file"
      - "traefik.http.services.site.loadbalancer.server.port=80"
    networks:
      - platform-network

  study:
    image: ghcr.io/imirjar/plyglo-expo:latest
    container_name: study
    platform: linux/amd64
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      Port: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.study.rule=Host(`study.plyglo.com`)"
      - "traefik.http.routers.study.entrypoints=websecure"
      - "traefik.http.routers.study.tls=true"
      - "traefik.http.routers.study.tls.certresolver=letsencrypt"
      - "traefik.http.routers.study.middlewares=chain-no-auth@file"
      - "traefik.http.services.study.loadbalancer.server.port=3000"
    networks:
      - platform-network

networks:
  platform-network:
    driver: bridge